changelog:
  exclude:
    labels:
      - 'ignore-for-release'
  categories:
    - title: '💥 Breaking Changes'
      labels:
        - 'breaking'
    - title: '✨ Features'
      labels:
        - 'feature'
    - title: '🐛 Bug Fixes'
      labels:
        - 'bugfix'
    - title: '📌 Dependencies'
      labels:
        - 'dependencies'
    - title: '📎 Other Changes'
      labels:
        - '*'
